apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-pod
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
      - name: flask-container
        image: tch1001/twig_server:v3.0.0
        env: 
          - name: NEO4J_SERVER_URL
            valueFrom:
              secretKeyRef: 
                name: flask-secret
                key: NEO4J_SERVER_URL
                optional: false
          - name: NEO4J_USERNAME
            valueFrom:
              secretKeyRef: 
                name: flask-secret
                key: NEO4J_USERNAME
                optional: false
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: flask-secret
                key: NEO4J_PASSWORD
                optional: false
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: LoadBalancer