apiVersion: apps/v1
kind: Deployment
metadata:
  name: keepalive-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keepalive-pod
  template:
    metadata:
      labels:
        app: keepalive-pod
    spec:
      containers:
      - name: keepalive-container
        image: neo4j:5.13.0
        command: ["/bin/sh", "-c", "while true; do echo 'MATCH (n:Project) WHERE id(n)=264 SET n.name=\"KEEP ALIVE WOOF\";' | cypher-shell -u $NEO4J_USERNAME -p $NEO4J_PASSWORD -a $NEO4J_SERVER_URL; sleep 5000; echo 'MATCH (n:Project) WHERE id(n)=264 SET n.name=\"KEEP ALIVE MEOW\";' | cypher-shell -u $NEO4J_USERNAME -p $NEO4J_PASSWORD -a $NEO4J_SERVER_URL; sleep 5000; done"]
        env: 
          - name: NEO4J_SERVER_URL
            valueFrom:
              secretKeyRef: 
                name: flask-secret
                key: NEO4J_SERVER_URL
                optional: false
          - name: NEO4J_USERNAME
            valueFrom:
              secretKeyRef: 
                name: flask-secret
                key: NEO4J_USERNAME
                optional: false
          - name: NEO4J_PASSWORD
            valueFrom:
              secretKeyRef: 
                name: flask-secret
                key: NEO4J_PASSWORD
                optional: false