version: '3.7'
networks:
  internal:
volumes:
  kratos-sqlite:
services:
  neo4j:
    image: neo4j:4.4.9
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/notneo4j"
      USERNAME: ${NEO4J_USERNAME}
      PASSWORD: ${NEO4J_PASSWORD}
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7474"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  kratos-migrate:
    image: oryd/kratos:v0.10.1
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ./containers/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - internal
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.10.1
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - kratos-sqlite:/var/lib/sqlite
      - ./containers/kratos:/etc/config/kratos
    networks:
      - internal
    healthcheck:
      # see: https://github.com/ory/kratos/issues/2524
      test: ["CMD-SHELL", "wget -q --spider http://localhost:4433/health/ready"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.11.0-alpha.0
    environment:
      - PORT=3000
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    dns:
      - 8.8.8.8
    networks:
      - internal
    ports:
      - "3000:3000"
    restart: on-failure
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - internal
