apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: traefik-ingress-controller
---
apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80
      nodePort: 30003
    - protocol: TCP
      name: admin
      port: 8080
      nodePort: 30004
    - protocol: TCP
      name: websecure
      port: 443
      nodePort: 30005
  selector:
    app: traefik
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.8
          args:
            # - --api.insecure
            # - --accesslog
            - --entrypoints.web.Address=:80
            # - --entrypoints.web.http.redirections.entryPoint.to=websecure
            # - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.websecure.Address=:443
            - --providers.kubernetescrd
            - --certificatesresolvers.myresolver.acme.dnschallenge=true
            - --certificatesresolvers.myresolver.acme.email=tanchienhao@gmail.com
            - --certificatesresolvers.myresolver.acme.storage=acme.json
            - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
            - --certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=0
          env:
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef: 
                  name: cloudflare-secret
                  key: CF_API_KEY
                  optional: false
            - name: CF_API_EMAIL
              valueFrom:
                secretKeyRef: 
                  name: cloudflare-secret
                  key: CF_API_EMAIL
                  optional: false
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080