neo4j:
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "neo4j-password-meowmeow"
  edition: "community"
  acceptLicenseAgreement: "yes"
  offlineMaintenanceModeEnabled: false

volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi