apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-kratos
data:
  kratos.yml: |
    version: v1.0.1

    # dsn: memory

    serve:
      public:
        base_url: https://twigslot.com/kratos
        cors:
          enabled: true
          allowed_origins:
            - https://twigslot.com
            - http://localhost:5173
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
      admin:
        base_url: http://kratos-service:4434/

    selfservice:
      default_browser_return_url: https://twigslot.com
      allowed_return_urls:
        - https://twigslot.com/auth

      methods:
        password:
          enabled: true

      flows:
        error:
          ui_url: https://twigslot.com/auth/error

        settings:
          ui_url: https://twigslot.com/auth/settings
          privileged_session_max_age: 15m
          after:
            default_browser_return_url: https://twigslot.com

        recovery:
          enabled: true
          ui_url: https://twigslot.com/auth/recovery

        verification:
          enabled: true
          ui_url: https://twigslot.com/auth/verification

        login:
          ui_url: https://twigslot.com/auth/login
          lifespan: 10m

        registration:
          lifespan: 10m
          ui_url: https://twigslot.com/auth/registration
          after:
            password:
              hooks:
                -
                  hook: session

    log:
      level: debug
      format: text
      leak_sensitive_values: true

    secrets:
      cookie:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE # TODO
      cipher:
        - 32-LONG-SECRET-NOT-SECURE-AT-ALL

    ciphers:
      algorithm: xchacha20-poly1305

    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/kratos/identity.schema.json

    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
  identity.schema.json: |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            },
            "name": {
              "type": "object",
              "properties": {
                "first": {
                  "title": "First Name",
                  "type": "string"
                },
                "last": {
                  "title": "Last Name",
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "email"
          ],
          "additionalProperties": false
        }
      }
    }