apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: twig-ingress-client
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`twigslot.com`) && !PathPrefix(`/auth`) && !PathPrefix(`/kratos`) && !PathPrefix(`/twig-api`) && !PathPrefix(`/autofill`)
    kind: Rule
    services:
      - name: nginx-service
        port: 80
  tls:
    secretName: acme-secret
    domains: 
    - main: twigslot.com
      sans:
      - staging2.twigslot.com
